/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author ricalv
 */
public class ComboBox extends javax.swing.JFrame {

    String ruta = "";
    URL url= null;
    ImageIcon icon = null;
    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListado = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        BotonOpcion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Selecciono la opcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(620, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Selecciona la opcion");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 956, -1));

        JListado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Opción 1", "Opción 2", "Opción 3", "Opción 4", "Opción 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JListado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 120, 70));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Herramienta", "Chequeo", "Otro" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        BotonOpcion.setText("opcion");
        BotonOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcionActionPerformed(evt);
            }
        });
        getContentPane().add(BotonOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int op = jComboBox1.getSelectedIndex();
        String cadena = jComboBox1.getSelectedItem().toString();
        
        switch (op) {
            case 0: mostrarImagen("/imagenes/4.png",op + 1,cadena);
                    break;
            case 1: mostrarImagen("/imagenes/5.png",op + 1,cadena);
                    break;
            case 2: mostrarImagen("/imagenes/6.png",op + 1,cadena);
                    break;
                    
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BotonOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcionActionPerformed
        int opc = JListado.getSelectedIndex();
        switch (opc){  
            case -1: JOptionPane.showMessageDialog(null,"No has seleccionado","Mensaje",
                    JOptionPane.WARNING_MESSAGE);
            
            break;
            case 0:
            case 1:
            case 2:
            case 3:  
            case 4: mostrarCuadro (opc+1);
               break;
        }
        
        
    }//GEN-LAST:event_BotonOpcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }
public void mostrarImagen(String urlImagen, int opcion, String cadena){
    url = this.getClass().getResource(urlImagen);
    icon = new ImageIcon(url);
     jLabel1.setIcon(icon);
     jLabel1.setText("Opción : "+ opcion + "Texto : "+ cadena);
    }
public void mostrarCuadro (int op){
JOptionPane.showMessageDialog(null, "Opción No: " + op,
                "Opción seleccionada",
                JOptionPane.INFORMATION_MESSAGE);}

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonOpcion;
    private javax.swing.JList<String> JListado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
